services:
  python_app:
    build: .  
    
    volumes:
      - .:/home/site/wwwroot  # Mount code into container, not needed for production

    ports:
      - "7071:80"
    env_file:
      - .env
    
    entrypoint: ["func", "host", "start", "--verbose"]

