services:
  python_app:
    build: .  
    
    volumes:
      - .:/home/site/wwwroot  # Mount code into container, not needed for production
 
    ports:
      - "7071:80"
    env_file:
      - .env
    # environment:
    #   - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
    
    entrypoint: ["func", "host", "start", "--verbose"]

