version: 1
formatters:
  simpleFormatter:
    format: "%(asctime)s - %(levelname)s - %(message)s"
handlers:
  rotatingFileHandler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simpleFormatter
    filename: calculate_embedding.log
    maxBytes: 10485760  # 10MB (10 * 1024 * 1024)
    backupCount: 5
root:
  level: INFO
  handlers: [rotatingFileHandler]