version: '3.8'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
        container_name: elasticsearch_demo_gambia
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
        ports:
            - "9200:9200"
        volumes:
            - es_data:/usr/share/elasticsearch/data

    loader:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: loader
        depends_on:
            - elasticsearch
      
    backend:
        image : pytorch/pytorch
        build:
          context: .
          dockerfile: Dockerfile
          platforms: 
            - linux/arm64
        container_name: fastapi
        depends_on:
            - elasticsearch
        
        ports:
            - "8000:8000"

        command: ["uvicorn", "search_api_endpoint:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


volumes:
  es_data:



