name: Check Embeddings

on:
  workflow_dispatch:
  push:
    paths:
      - 'jobs/calculate-embeddings/**'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jobs/calculate-embeddings
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python -m nltk.downloader punkt_tab
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: jobs/calculate-embeddings
      # We run the script on epiverse-trace to go faster
      - run: python save_embeddings_locally.py epiverse-trace
      - run: pip install pytest
      - run: python pytest tests/test_embeddings_output.py
