name: Check Embeddings

on:
  push:
    paths:
      - 'jobs/calculate-embeddings/**'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jobs/calculate-embeddings
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: jobs/calculate-embeddings
      - run: python save_embeddings_locally.py
      - run: pip install pytest
      - run: python pytest tests/test_embeddings_output.py
